spring:
  application:
    name: course-management
  datasource:
    url: jdbc:mysql://localhost:3306/sgc?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: Camilo
    password: 12345
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true